### ISSUE TITLE
Add stop() method to query, projection and read model projection

### ISSUE THREAD

**Issue by prolic** [prooph/pdo-event-store#10]

**Comment by basz** [comment]
can you explain what need to be done?

**Comment by prolic** [comment]
1) Add a method stop(): void to Query, Projection & ReadModelProjection interface
2) Implement the method
3) Add tests

Goals:
If someone calls `$this->stop()` while processing messages, the query / projection gets stopped after state persisted. No further messages are processed.

**Comment by basz** [comment]
I'll have a look. to be added to the 'projections' PR?

**Comment by prolic** [comment]
No develop branch - projections are merged now.

**Comment by basz** [comment]
should the stop method be added to interfaces in the event-store?

**Comment by prolic** [comment]
yes!

**Comment by prolic** [comment]
start with InMemoryEventStoreQuery and go from there

**Comment by basz** [comment]
ok, looked at it. not entirely sure what I'm doing... :-)

Quick questions:

- Query don't persist state now do they?
- A call to `stop` should simply be a mark `isStopped` that the `run` methods check...

```
public function stop(): void {
    $this->isStopped = true;
}
```
and in each run() method simply

```
foreach ($this->position->streamPositions() as $streamName => $position) {
            if ($this->isStopped) {
                break;
            }
```
Each `$this->handleStream***` method persists its own state, right? I don't need to do that right?

Assuming the above is correct, how would I go about testing this. I mean, how can I call stop after say 10 events have been processed if the run goes into a foreach.

**Comment by prolic** [comment]
Correct. I added tests with usercreated and changed name. So test by
counting events and on name changed call stop after counting. So state
should have Count = 2

Am 18.11.2016 19:26 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by basz** [comment]
can be closes as no changes are required if i am not mistaking
