### ISSUE TITLE
Usage of PDO::rowCount() with SELECT statements

### ISSUE THREAD

**Issue by uirapuru** [prooph/pdo-event-store#113]
https://github.com/prooph/pdo-event-store/blob/8780fd9431a539504583f569df2c359abcc413ff/src/MySqlEventStore.php#L331

Maybe not issue (well, happened for me to return wrong result, but it was really specific case...), but in docs for PDO::rowCount() we find:

 > If the last SQL statement executed by the associated PDOStatement was a SELECT statement, some > databases may return the number of rows returned by that statement. However, this behaviour is not > guaranteed for all databases and should not be relied on for portable applications.

this is more as a reminder. Thanks, great job with Prooph!

**Comment by prolic** [comment]
We have unit tests covering that case, so we can assume it's working as intended, thanks.
