### ISSUE TITLE
Wrong position in projections table

### ISSUE THREAD

**Issue by Adapik** [prooph/pdo-event-store#114]
How to reproduce:

1) Trigger a `ConcurrencyException`. It's not very easy to trigger but I wrote a test number 8 in https://github.com/Adapik/event-store-benchmarks/tree/reproduces-a-projection-bug. The idea is simple - to write events for the SAME aggregate in parallel transactions. If they a parallel enough (thx to pthreads they are) a ConcurrencyException is thrown (as it should be). Note that persisting strategy is `PostgresSingleStreamStrategy`. But in Postgres `nextval()` of sequence is non-transactional. Thus for failed transactions we increment `no` but not inserting event.

2) Run the projection on event_store and look at projection position in table `projection`. Projector actually counts events handled and the position is equal to events count in event_store. But events loaded for event_store by condition `no > :no`. As a result some events proceed multiple times. See also (https://github.com/prooph/proophessor-do-symfony/issues/17)

How to run my test: `docker-compose -f docker-compose-postgres.yml run --rm php -f /app/src/benchmark.php`. The output is at the end. The interesting part is:

> Events count: 165
> Max no: 4501
> Position: {"event_stream": 165}

The idea of fix is to write in `projection` table number ('no') of last event projected.
PR is here https://github.com/prooph/pdo-event-store/pull/115

**Comment by sandrokeil** [comment]
@prolic Do you remember our discussion for the ArangoDB event store and number gaps? Conclusion was, gaps are no problem.

**Comment by prolic** [comment]
@sandrokeil yes, @Adapik has a fix for the projection stuff, but I want to check again and make sure there is no further problem.
