### ISSUE TITLE
Missing backticks on table names declarations (mysql)

### ISSUE THREAD

**Issue by basz** [prooph/pdo-event-store#128]
whilst testing the standard category projections I ran into an insertion issue

```
Error 42000. Maybe the event streams table is not setup?
Error-Info: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-customer.customerWasCreated (event_id, event_name, payload, metadata, created_a'
```

Probably due to the fact that I use dot's in message names (denoting the bounded context.

simply adding backticks solved this... PR?

**Comment by prolic** [comment]
Yes, PR and test please :-)
Good catch

**Comment by basz** [comment]
hmm. I now noticed I had put this in my strategy 

```
public function generateTableName(StreamName $streamName): string
    {
        return 'events_' . $streamName->toString();
        //return '_' . sha1($streamName->toString());
    }
```

Therefor tests will always pass. Need to support people who do bring own stragegies? I must say I find it useful to traverse events manually.

**Comment by prolic** [comment]
You can still traverse streams by looking up the event_streams table. There
you'll find the stream name -> real stream name mapping. By default _ +
sha1 hash is used, hence the 41 chars. You can create custom stream
strategies if you want to and have custom create table thingys, too.

Sascha-Oliver Prolic

2018-02-03 4:04 GMT+08:00 Bas Kamer <notifications@github.com>:

**Comment by prolic** [comment]
@basz Are you going to provide a test case and PR? I would like to release next minor version soon.

**Comment by basz** [comment]
Mayby this afternoon otherwise monday

**Comment by prolic** [comment]
Same applies probably also to MariaDB (and Postgres?). Even if you don't have them installed, simply put your change to `https://github.com/prooph/pdo-event-store/blob/master/tests/AbstractPdoEventStoreTest.php` and then travis will tell you it's results for all db vendors. Just apply the tests first, submit PR, then apply the fix in a second commit after travis has run. This way you get pre/post results without having to install MariaDB and Postgres (and you don't even need download a bunch of docker-images, which avoids this obviously).

**Comment by basz** [comment]
Runnning docker already, so im good. Just not sure if i can come up wit a test if im not using mu own strategie. Not sure if you would want a custom strategy in the tests...

**Comment by prolic** [comment]
Sure, why not use a custom strategy. Just add it as test-asset.
