### ISSUE TITLE
Data too long for column 'stream_name'

### ISSUE THREAD

**Issue by basz** [prooph/pdo-event-store#129]
Error 22001. Maybe the event streams table is not setup?
Error-Info: Data too long for column 'stream_name' at row 1

Looking at the definition for stream_name may only have 41 chars? Why so short? Why this number?

https://github.com/prooph/pdo-event-store/blob/master/scripts/mariadb/01_event_streams_table.sql#L4
https://github.com/prooph/pdo-event-store/blob/master/scripts/mysql/01_event_streams_table.sql#L4
https://github.com/prooph/pdo-event-store/blob/master/scripts/postgres/01_event_streams_table.sql#L4

**Comment by prolic** [comment]
see https://github.com/prooph/pdo-event-store/issues/128
