### ISSUE TITLE
Upgrade locking mechanism

### ISSUE THREAD

**Issue by prolic** [prooph/pdo-event-store#145]
Locking mechanism can be updated like in prolic/awesomeness. No lock-timeout is needed. Hopefully that's possible without BC.

**Comment by codeliner** [comment]
better to discuss this option in the correct issue:

> @prolic changing the lock mechanism is a bc break. Isn't it?

**Comment by prolic** [comment]
Not sure. From end user perspective nothing changes, only internals are
affected.

**Comment by codeliner** [comment]
Also what happens if lock cannot be released? Throwing an exception might not be a good solution. You end up in a deadlock, right?

With the current solution another projection process can take over when lock timeout is reached.

> Not sure. From end user perspective nothing changes, only internals are
affected.

But db schema changes

**Comment by prolic** [comment]
If connection is closed, lock is gone immediately. Nothing to worry. New
schema would not have lock_until column, existing columns just stay, they
are not a problem.

**Comment by codeliner** [comment]
ok sounds good, but I'm not a database expert. Not sure if we can change behavior without some stress tests ...

**Comment by codeliner** [comment]
We can create an experimental feature branch and ask a few people if they can test the modified projection  lock mechanism in their projects. If we get positive feedback, I'm ok with it

**Comment by prolic** [comment]
`binlog_format` default value is `ROW`. But we can add another hint in the documentation, that you should not change that.

The timeout should be 0, that's still a bug in prolic/awesomeness

**Comment by prolic** [comment]
closing this now. reason: it's not possible to do without any BC breaks, I see any limitations on mysql server settings after the fact as a BC. This will only be changed in new major release.
