### ISSUE TITLE
OPTION_UPDATE_LOCK_THRESHOLD does not work with values greater 1000 

### ISSUE THREAD

**Issue by fritz-gerneth** [prooph/pdo-event-store#146]
Played around a bit with this new option, setting values to:
```
                    PdoEventStoreReadModelProjector::OPTION_LOCK_TIMEOUT_MS => 20000,
                    PdoEventStoreReadModelProjector::OPTION_UPDATE_LOCK_THRESHOLD => 15000,
```

This causes the next update tick to be calculated incorrectly to a value of f=0.15 , hence causing lock updates more frequently than configured. 
This behavior becomes pretty apparent when using `OPTION_UPDATE_LOCK_THRESHOLD = 1000`. This causes the fraction to become `1`.

Workaround is to set the seconds art of the threshold as well:
```
        $updateLockThreshold->s = floor($this->updateLockThreshold / 1000);
        $updateLockThreshold->f = ($this->updateLockThreshold % 1000) / 1000;
```
If course this then causes the same issues when using values larger than `60000` (as we'd have to modify the minute flag). Yet there seems to be no easy way to add any amount of milliseconds to the interval directly.

**Comment by prolic** [comment]
@codeliner?

**Comment by fritz-gerneth** [comment]
Weird enough this seems to be correct for small values. For anything greater 7000 this seems to be drifting away though: https://3v4l.org/tIW08 
E.g. for values of 20000 (add 20 seconds), the added value seems to be aligning to somewhere arround 7seconds. Not exactly sure I fully understand what is going on there or it is just me with wrong assumptions here :)

**Comment by codeliner** [comment]
@fritz-gerneth good catch :+1: 

See those two lines:

```
Value: 2018-04-30T16:07:59.923456 - Diff: 06:800000 - Expected: 6.8
Value: 2018-04-30T16:07:59.1023456 - Diff: 06:900000 - Expected: 6.9
```
Instead of increasing the minute, something weird happens here.

**Comment by prolic** [comment]
I think you have to either create `DateInterval` more granular (seconds + minutes) or let it create by using diff on a `DateTime`-object. If you create a `DateInterval`-object and assign too big numbers to seconds / milliseconds, it doesn't care, and just does it.

**Comment by codeliner** [comment]
> let it create by using diff on a DateTime-object.

This doesn't work for milliseconds so yes, we need to calculate minutes/seconds and create the interval with those values then add split seconds ... What a mess :cry:

**Comment by prolic** [comment]
Maybe we limit the value to something, so max value is 5mins f.e., so we
don't need to handle hours, days, weeks, etc (which wouldn't make sense
either)

**Comment by codeliner** [comment]
59 min ?

**Comment by prolic** [comment]
Ok

On Apr 30, 2018 23:53, "Alexander Miertsch" <notifications@github.com>
wrote:

59 min ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/prooph/pdo-event-store/issues/146#issuecomment-385442087>,
or mute the thread

**Comment by codeliner** [comment]
ah wait this one works: https://3v4l.org/aBjB3

**Comment by codeliner** [comment]
looks like we just need to set seconds correctly

**Comment by codeliner** [comment]
@prolic @fritz-gerneth can we go with this solution? https://3v4l.org/JPAYn

**Comment by prolic** [comment]
I see this:
`Value: 2018-04-30T16:07:54.023456 - Diff: 01:-100000 - Expected: 0.9`

**Comment by codeliner** [comment]
1 - 0.1 = 0.9 ;)

**Comment by codeliner** [comment]
just look at the time that is constantly increased by 100 ms. We are only interested in this. The diffing was just added by @fritz-gerneth to illustrate the issue

**Comment by fritz-gerneth** [comment]
The notion is a bit weird to describe `900` by `1000 - 100` but this does not seem to be the only place for this :) 
Anyways the solution indeed seems to be to set the seconds correctly, either by property of throughout the initial interval as @codeliner showed. Haven't tested the behavior with large seconds values thought. Might be working correctly when createing an interval with 4000 seconds.

**Comment by codeliner** [comment]
@fritz-gerneth looks good with 4000 s: https://3v4l.org/n0gdl

**Comment by codeliner** [comment]
@prolic changes the lock mechanism is a bc break. Isn't it?

**Comment by prolic** [comment]
Not sure. From end user perspective nothing changes, only internals are
affected.

**Comment by fritz-gerneth** [comment]
Awesome. Thanks for the fast fix & feature in the first place! :)

**Comment by codeliner** [comment]
@fritz-gerneth thx for your fast bug report and great demonstration of the problem. I really enjoyed this bug hunting session! This is the real power of open source :heart:
