### ISSUE TITLE
Key value mapping in indexedMetadataFields required

### ISSUE THREAD

**Issue by prolic** [prooph/pdo-event-store#150]
Current implementation uses substr to map _aggregate_id to aggregate_id. Problem is, users are free to index other metadata fields as well, so they can index a field named 'house', but would need to generate a field named 'ouse'. But what if they have another field named 'mouse' that needs to be indexed as well? As you see, the substr solution was not that a good idea.

Unfortunately I released this yesterday and changing again is a BC. I would however still want to change it, because the problem is real and not solvable with current release and also the current release is a BC because of 'house' -> 'ouse' naming needs. And lf course, the release is only one day old....

Thoughts? @codeliner @kochen

**Comment by sandrokeil** [comment]
I think it's a bugfix and not a BC break if we change it back. Simple question: Why not only remove first sign if it is an underscore?

**Comment by prolic** [comment]
That's a good idea. However you could have a metadata field 'one' and
generate an indexed column 'two'. Unlikely, but possible.

**Comment by kochen** [comment]
@prolic yes, you are right, but that it only possible on (any) `CustomMariaDBPersistenceStrategy`) so for the `prooph` component itself it's "safe" enough.

We could easily introduce the mapping, just like I did in the first proposed commit of the fix: 
https://github.com/prooph/pdo-event-store/pull/149/commits/f25eefcf42d324192d0fb7be7cad0ee1a4daecf2

But for a more future proof solution, I think we should be able to check/validate that mapping also when the DB Table is created.

**Comment by prolic** [comment]
So either we roll back to your first commit, or we substr only when first character is '_'. What do you think?

**Comment by kochen** [comment]
I wouldn't rollback as it's not a full implementation, but we could "fix" it into that way.

I did add a comment in the README about this for CustomStrategy implementer.
So, what I think is better, is to actually leave it as is for now, and think of a proper solution for the next major release, with any potential BC that might occur.

**Comment by prolic** [comment]
Don't worry about next major release, because it will not have any persistence strategies at all.

the substr solution is really bad, because it denies custom indexes. if we agree to at least only remove first character if it's `_`, then we can still allow custom indexes.

**Comment by kochen** [comment]
I can easily change the substr with a mapping, with the assumption that the `indexedMetadataFields` has a correctly formatted mapping.

```
    public function indexedMetadataFields(): array
    {
        return [
            '_aggregate_id' => 'aggregate_id',
            '_aggregate_type' => 'aggregate_itype,
            '_aggregate_version' => 'aggregate_version',
        ];
    }
```

and then in `convertToColumn` (something like):
```
$indexedColumns = $this->persistenceStrategy->indexedMetadataFields();
if (in_array($match['field'], array_keys($indexedColumns))) {
    $match['field'] = indexedColumns[$match['field']];
    $match['fieldType'] = FieldType::MESSAGE_PROPERTY();
}
```

**Comment by kochen** [comment]
Shall I just provide an initial PR?

**Comment by prolic** [comment]
yes please

**Comment by kochen** [comment]
done
