### ISSUE TITLE
MariaDB 10.2.16 causes issues

### ISSUE THREAD

**Issue by codeliner** [prooph/pdo-event-store#164]
During release of pdo-event-store 1.9 we encountered errors testing mariadb.
BETA was tested against mariadb 10.2.15 and everything worked fine. But now with mariadb 10.2.16 being available our travis build fails: https://travis-ci.org/prooph/pdo-event-store/jobs/398146743

We were able to reproduce the bug locally using official mariadb docker images:
mariadb 10.2.15 :heavy_check_mark: 
mariadb 10.2.16 :no_entry_sign: 

**We try to identify the exact problem. For now, don't use mariadb 10.2.16 with pdo-event-store!!!**

**Comment by gquemener** [comment]
Here are the steps to reproduce the phpunit errors locally:

``` bash
$ git clone git@github.com:prooph/pdo-event-store.git
$ cd pdo-event-store
$ docker run --rm -ti -v "$PWD":/app --user "$(id -u):$(id -g)" -w /app composer install --ignore-platform-reqs
$ docker run --rm -ti -p "3306:3306" -e MYSQL_ALLOW_EMPTY_PASSWORD=yes --name pdo-event-store-mariadb -d mariadb:10.2.16
$ docker exec -it pdo-event-store-mariadb mysql -e 'create database event_store_tests;'
$ cp phpunit.xml.mariadb phpunit.xml
$ sed -i 's/127.0.0.1/pdo-event-store-mariadb/g' phpunit.xml
$ docker run --rm -ti -v "$PWD":/app -w /app --user "$(id -u):$(id -g)" --link "pdo-event-store-mariadb" prooph/php:7.1-cli vendor/bin/phpunit
$ docker kill pdo-event-store-maria-db
```

And here's the diff between https://github.com/MariaDB/server/compare/mariadb-10.2.15...mariadb-10.2.16 (if of any help).

**Comment by basz** [comment]
remark. I found I needed 10.2.14 not 10.2.15 to get the tests working. So, 10.2.14 one would need.

**Comment by drgomesp** [comment]
I can confirm what @basz says, as I also ran into the same errors with **10.2.15**.

**Comment by prolic** [comment]
Failed asserting that 5 matches expected 49


That's because of a bugfix in eventstore I guess. See latest release

**Comment by basz** [comment]
MariaDB version | Result
------------ | -------------
mariadb:10.2.14 | OK (394 tests, 2183 assertions)
mariadb:10.2.15 | OK (394 tests, 2183 assertions)
mariadb:10.2.16 | Tests: 394, Assertions: 2167, Errors: 8. *(same output as above)*

10.2.15 seems good after all.

note: all done with `composer update` and `docker-compose -f docker-compose-tests.yml down --rmi all -v --remove-orphans` in-between runs.

**Comment by gquemener** [comment]
Currently debugging this, I'll leave my notes here to keep track of them.

I've detected a difference in the behavior of the `json_value` function between 10.2.15 and 10.2.16.
(Note: this function is used to load events with a metadata matcher [here](https://github.com/prooph/pdo-event-store/blob/master/src/MariaDbEventStore.php#L699)).

As a matter of fact,
the query `SELECT json_value('{"foo":true}', '$.foo');` will return

10.2.15
```
MariaDB [none]> SELECT json_value('{"foo":true}', '$.foo');                                                                                                                                          
+-------------------------------------+
| json_value('{"foo":true}', '$.foo') |
+-------------------------------------+
| true                                |
+-------------------------------------+
1 row in set (0.00 sec)

```

10.2.16
```
MariaDB [(none)]> SELECT json_value('{"foo":true}', '$.foo');
+-------------------------------------+
| json_value('{"foo":true}', '$.foo') |
+-------------------------------------+
| 1                                   |
+-------------------------------------+
1 row in set (0.00 sec)
```

**Comment by gquemener** [comment]
It looks like it's been done on purpose (aka feature, not a bug) => https://github.com/MariaDB/server/commit/352c7e0dfaa0f121c5b35e1d9fafb9ec8897e768
