### ISSUE TITLE
deleting running projections will not restart from event 0

### ISSUE THREAD

**Issue by basz** [prooph/pdo-event-store#168]
When I have a projection running that is instructed to delete with deletion projections are not removed until *all* events have been processed. 

I would expect it would finish projecting events within the batch size configuration option to then delete and restart.

discovered this via snapshots which are also read model projections.

Looking at the code this seems to be true for all status changes (stop, delete and reset) as the method `handleStreamWithSingleHandler` does not check for status at all.

I've experimented a bit to fix this inside the `handleStreamWithSingleHandler` method, but it's not as simple as calling this->reset(). One possible solution seems to be to simply stop when status is not running.

**Comment by prolic** [comment]
@basz can this be closed now?

**Comment by basz** [comment]
Closing per #170
