### ISSUE TITLE
Resetting projection during event processing behaves incorrectly 

### ISSUE THREAD

**Issue by grzegorzstachniukalm** [prooph/pdo-event-store#176]
The behavior of PdoEventStoreReadModelProjector on resetting is different during event processing and event loading

when i'm resetting projection during stream handling, projection is stopped due to 
```php
/// Line 583:585 and 624:626 of /Projection/PdoEventStoreReadModelProjector.php
if (! $this->status->is(ProjectionStatus::RUNNING()) && ! $this->status->is(ProjectionStatus::IDLE())) {
    $this->isStopped = true;
}
```

```php
// Line 521 of /Projection/PdoEventStoreReadModelProjector.php
while ($keepRunning && ! $this->isStopped);
```

**Comment by prolic** [comment]
I don't understand what you are asking for.

**Comment by grzegorzstachniukalm** [comment]
Please restore isStopped property to false after resetting projector

**Comment by basz** [comment]
I dont believe so. Afaik the process does  not stop after resetting.

**Comment by basz** [comment]
Could you provide a PR and test?

**Comment by basz** [comment]
I had a look already. Does this test describe the issue? Please use it in *EventStoreProjectorTest.php and *EventStoreReadModelProjectorTest if so.

(note that: prepareEventStream('user') prepares 50 events and after resetting it *once* it should start over, hence counting 70 events)

```
    /**
     * @test
     */
    public function a_running_projector_that_is_reset_should_keep_stream_positions(): void
    {
        $this->prepareEventStream('user');

        $projectionManager = $this->projectionManager;
        $projection = $projectionManager->createProjection('test_projection');

        $eventCounter = 0;
        $projection
            ->fromStream('user')
            ->init(function () {
                return [];
            })
            ->whenAny(
                function (array $state, Message $event) use (&$eventCounter, $projectionManager) {
                    $eventCounter++;

                    if (20 === $eventCounter) {
                        $projectionManager->resetProjection('test_projection');
                    }

                    return $state;
                }
            )
            ->run(false);

        $this->assertEquals(70, $eventCounter);
    }
```

**Comment by grzegorzstachniukalm** [comment]
> I had a look already. Does this test describe the issue? Please use it in *EventStoreProjectorTest.php and *EventStoreReadModelProjectorTest if so.
> 
> (note that: prepareEventStream('user') prepares 50 events and after resetting it _once_ it should start over, hence counting 70 events)
> 
> ```
>     /**
>      * @test
>      */
>     public function a_running_projector_that_is_reset_should_keep_stream_positions(): void
>     {
>         $this->prepareEventStream('user');
> 
>         $projectionManager = $this->projectionManager;
>         $projection = $projectionManager->createProjection('test_projection');
> 
>         $eventCounter = 0;
>         $projection
>             ->fromStream('user')
>             ->init(function () {
>                 return [];
>             })
>             ->whenAny(
>                 function (array $state, Message $event) use (&$eventCounter, $projectionManager) {
>                     $eventCounter++;
> 
>                     if (20 === $eventCounter) {
>                         $projectionManager->resetProjection('test_projection');
>                     }
> 
>                     return $state;
>                 }
>             )
>             ->run(false);
> 
>         $this->assertEquals(70, $eventCounter);
>     }
> ```

You almost got it, it is about keepRunning Projection, thanks for snippet, i added it to tests with small change :)
