### ISSUE TITLE
Projection with end2end tests

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [prooph/pdo-event-store#183]
Hi all, I would like to add some end2end test with phpunit into my symfony app.

So I would like to call an api url and check the response.

Inside the api url there is a call to a projection. So I need to start it with a command like this:

```
bin/console event-store:projection:run post_projection
```

If I launch a script test like this:

```
bin/console event-store:event-stream:create --env=test
bin/console event-store:projection:run post_projection --env=test -d
./bin/phpunit --stop-on-failure
```

I get this error:

```
Base table or view not found: 1146 Table 'symfony4_prooph.read_post' doesn't exist
```

If I make the call with Postman and launch my projection command it works fine.
So the problem is how to use it in tests.

Can someone help me please?

**Comment by prolic** [comment]
Maybe just a bug in the symfony bundle? Can you debug this?

**Comment by AlessandroMinoccheri** [comment]
The problem is that you need to launch the command to run projection that remain in pending..
So I have found this solution to launch tests correctly

```
# other commands
bin/console event-store:projection:run post_projection --env=test &
bin/phpunit --stop-on-failure
bin/console event-store:projection:stop post_projection --env=test &
```

In this way the run process comand is in background

**Comment by prolic** [comment]
Great, so can we close this issue?

**Comment by AlessandroMinoccheri** [comment]
Yes. I don't like this solution but at the moment it works
