### ISSUE TITLE
Use tablespaces?

### ISSUE THREAD

**Issue by PatchRanger** [prooph/pdo-event-store#193]
I could be wrong or missing something - but here is the concern I have:
- Current event-store implementation implies large number of tables: one per entity. It is configurable (on/off) - but nevertheless.
- https://www.percona.com/blog/2017/10/01/one-million-tables-mysql-8-0/ : MySQL and MariaDB are pretty "sceptic" about having large counts of tables. I mean, their internal structure do not fit the case.
- https://www.percona.com/blog/2016/10/03/mysql-8-0-general-tablespaces-file-per-database-no-frm-files/ : There is a "recipe" - using tablespace (instead of name prefixes) should be fine for both MySQL and MariaDB.

Interesting thing is that PostgreSQL also has a concept of tablespaces.

Could we replace prefix-based category determination with tablespaces? Is this a meaningful feature-request?)

**Comment by prolic** [comment]
I'm worried this would be a BC break.

**Comment by PatchRanger** [comment]
@prolic I understand. Let's plan it as a feature for next major release? I could be considering promoting usage of the event-sourcing in general and your library in particular at my work - but this point is crucial in terms of deployment: we already have millions of rows and millions of tables sound worrying, if we keep in mind concerns I explained above.

**Comment by prolic** [comment]
If the amount of tables is a concern, then use the single stream strategy (with one table per aggregate or one table for all events).
The next major release is already in the pipeline and this will not be a problem anymore.

**Comment by prolic** [comment]
By the way: the single stream strategy is already the recommended one in the docs and not one table per aggregate as you suggested.
