### ISSUE TITLE
Projection fails sometimes when lock timeout is less than 100ms

### ISSUE THREAD

**Issue by brunowowk** [prooph/pdo-event-store#198]
https://github.com/prooph/pdo-event-store/blob/01b2cf3d30c1d01a7ad87cc00eb968de97c9c79a/src/Projection/PdoEventStoreProjector.php#L991-L1001

sometimes, on the start of a second, the value in microseconds plus the timeout will have less than 6 digits (when the timeout alone doesn't have at least 100000 microseconds), then `\substr($micros, 0, -6)` will return false and modify will fail:

```
DateTimeImmutable::modify(): Failed to parse time string (+ seconds) at position 0 (+): Unexpected character
```

**Comment by brunowowk** [comment]
And maybe we could add some early returns to ignore this whole projection lock mechanism when the timeout is 0. This could be useful if we decide to manage projection concurrency on our own.

**Comment by prolic** [comment]
wanna provide a PR?

**Comment by brunowowk** [comment]
Actually, I just wanted to rant, drop the issue and be done about it

Haha sorry, I was in the middle of something when I found out about this so I just documented it to get back later. OFC I forgot about it shortly after :P

Here you go (: #206

**Comment by prolic** [comment]
see https://github.com/prooph/pdo-event-store/releases/tag/v1.11.1
