### ISSUE TITLE
Drop support of PHP 7.1 (EOL: 2020-01-01)

### ISSUE THREAD

**Issue by gquemener** [prooph/pdo-event-store#218]
https://www.php.net/supported-versions.php

What about dropping 7.2 at the same time as it's not actively supported as well? :thinking:

**Comment by gquemener** [comment]
I'll have a look at the RDBMS support releases as well.

**Comment by fritz-gerneth** [comment]
I'd caution against doing so unless there is some actual requirement to do so. Older versions of PHP are still supported by some distributions by backports of security fixes (RHEL / Debian Stretch)

**Comment by gquemener** [comment]
Thanks @fritz-gerneth, I'll look into that as well.

For the record, PHPUnit is about to drop support of php 7.1 as well in a few months: https://phpunit.de/supported-versions.html
