### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by patrickkusebauch** [prooph/pdo-event-store#229]
Self-explanatory. Not sure if there is any blocker other than the `composer.json` definition. I might be able to look into it for you, but right now I am in the process of going through all the packages in my project needing an upgrade. Once done, I can start focusing on external dependancies.

**Comment by codeliner** [comment]
PHP 8 support is available now: https://github.com/prooph/pdo-event-store/releases/tag/v1.13.0
