### ISSUE TITLE
What's the reasoning behind the current maximum length for event names?

### ISSUE THREAD

**Issue by MetalArend** [prooph/pdo-event-store#231]
Currently almost all implementations of the `PostgresPersistenceStrategy` have a hard-coded maximum length of 100 characters for the event_name. Is there a reason to keep this hard-coded to 100? Or is there some other limit we must keep in mind to make sure no other code trips over longer event names?

**Comment by prolic** [comment]
You can change this length according to your needs.There is no requirement to have a certain length.
