### ISSUE TITLE
Should resetProjection always be called?

### ISSUE THREAD

**Issue by codeliner** [prooph/pdo-event-store#38]
I'm wondering if [this line](https://github.com/prooph/pdo-event-store/blob/master/src/Projection/PdoEventStoreReadModelProjection.php#L327) should be moved above the [if block](https://github.com/prooph/pdo-event-store/blob/master/src/Projection/PdoEventStoreReadModelProjection.php#L315) so that `$this->resetProjection()` gets called even if the initCallback returns a state array?

**Comment by prolic** [comment]
No, it doesn't matter if a callback is provided or not. If you call `reset()` on a read model projection, the read model needs to be reset.

**Comment by prolic** [comment]
Thx
