### ISSUE TITLE
MySql EventStore does not support transactions

### ISSUE THREAD

**Issue by basz** [prooph/pdo-event-store#39]
Adding the TransactionManager Plugin to a MySqlEventStore should throw an exception as it can only be used by Postgres.

Currently it runs out of memory

**Comment by prolic** [comment]
@basz how did you do that? The TransactionManager has a typehint for `TransactionalEventStore` in the constructor, and the `MySqlEventStore` does not implement that interface. So PHP should throw already.

**Comment by basz** [comment]
I don't remember. When i try it now it indeed dies: `PHP Fatal error:  Uncaught TypeError:`
