### ISSUE TITLE
SingleStreamStrategy should select using generated columns to utilise the indexes

### ISSUE THREAD

**Issue by basz** [prooph/pdo-event-store#42]
Even when using the the virtual generated columns with indexes (SingleStreamStrategy) the indexes aren't utilised. 

example of an expected query
```
SELECT * FROM _7794a224f85453058cf637d52e7c4487568a8271 WHERE no >= 30031 AND `aggregate_type` = 'HF\\Model\\Domain\\Dossier\\Aggregate\\Dossier' AND `aggregate_id` = '43f4f846-dd2f-569a-a95d-df139ce9718c' AND `version` > 0 ORDER BY no ASC LIMIT 1001;
```
*Query took 0.0824 seconds*

actual query performed
```
SELECT * FROM _7794a224f85453058cf637d52e7c4487568a8271 WHERE no >= 30031 AND metadata->"$._aggregate_type" = 'HF\\Model\\Domain\\Dossier\\Aggregate\\Dossier' AND metadata->"$._aggregate_id" = '43f4f846-dd2f-569a-a95d-df139ce9718c' AND metadata->"$._aggregate_version" > 0 ORDER BY no ASC LIMIT 1001
```
*Query took 0.1206 seconds*

**Comment by basz** [comment]
I could try to fix this, but I am not sure what's the best approach. 

I think Prooph\EventStore\Pdo\PersistenceStrategy should provide a method such as 'generatedColumnNames' returning (metadata) columns that are indexed (`version`, `aggregate_id`, `aggregate_type`) and that these loops https://github.com/prooph/pdo-event-store/blob/master/src/MySqlEventStore.php#L273-L285, https://github.com/prooph/pdo-event-store/blob/master/src/MySqlEventStore.php#L345-L357 should be split in two foreach loops. One for the mentioned generated fields (they should be first i'm guessing so the AND matcher will break on those columns as soon as possible) and then for any other metadata fields that might be present in the MetadataMatcher.

**Comment by sandrokeil** [comment]
@basz What is the output of the `explain` statement?

**Comment by basz** [comment]
```
mysql> EXPLAIN SELECT * FROM _7794a224f85453058cf637d52e7c4487568a8271 WHERE no >= 30031 AND metadata->"$._aggregate_type" = 'HF\\Model\\Domain\\Dossier\\Aggregate\\Dossier' AND metadata->"$._aggregate_id" = '43f4f846-dd2f-569a-a95d-df139ce9718c' AND metadata->"$._aggregate_version" > 0 ORDER BY no ASC LIMIT 1001;
+----+-------------+-------------------------------------------+------------+-------+---------------+---------+---------+------+-------+----------+-------------+
| id | select_type | table                                     | partitions | type  | possible_keys | key     | key_len | ref  | rows  | filtered | Extra       |
+----+-------------+-------------------------------------------+------------+-------+---------------+---------+---------+------+-------+----------+-------------+
|  1 | SIMPLE      | _7794a224f85453058cf637d52e7c4487568a8271 | NULL       | range | PRIMARY       | PRIMARY | 4       | NULL | 28516 |   100.00 | Using where |
+----+-------------+-------------------------------------------+------------+-------+---------------+---------+---------+------+-------+----------+-------------+
1 row in set, 1 warning (0.00 sec)

```

**Comment by basz** [comment]
ok. i messed up... metadata->"$._aggregate_version" is not `aggregate_version` but `version`. let me check

**Comment by basz** [comment]
aaarg... closing: no fix needed...

```
It is important to note that as demonstrated in EXPLAIN, both variations of the above query will use an index. That is to say that the optimizer will look for compatible[1] virtual columns with indexes that match the expression in JSON queries.
```
from: http://mysqlserverteam.com/indexing-json-documents-via-virtual-columns/

I do see performance drop a lot after the first 10000 events... then again this is a tiny dev machine... i should probably tune mysql somehow...

**Comment by codeliner** [comment]
@basz Even if you close this specific issue the kind of analyzes are needed and very useful :+1:
