### ISSUE TITLE
Improve documentation SingleStreamStrategy

### ISSUE THREAD

**Issue by hiddeco** [prooph/pdo-event-store#73]
This library is lacking documentation regarding the migration / initialisation of `SingleStreamStrategy` tables, which makes it a bit hard to integrate without asking for help.

A snippet of documentation that pushes you in the right direct can be found here:  https://github.com/prooph/event-store/blob/master/examples/quickstart.php#L63-L66 and a semi-solution by @basz can be found here: https://gitter.im/prooph/improoph?at=58f6085d69a692963ec003df

**Comment by prolic** [comment]
@hiddeco wanna provide a PR?
