### ISSUE TITLE
Consider adding support for TimescaleDB

### ISSUE THREAD

**Issue by codeliner** [prooph/pdo-event-store#74]
TimescaleDB looks interesting: http://www.timescale.com/
It is a Postgres extension optimized for time series data. An event stream fits into that use case and their docs state that you use normal Postrgres SQL for reads and writes. Would be interesting if it can be used as a drop in replacement for standard Postrges pdo event store

**Comment by stalltron** [comment]
Should be really easy to add support, very little to actually do:

1. [Install extension to existing DB](http://docs.timescale.com/getting-started/installation) 
2. CREATE TABLE new_table (LIKE ordinary_table);   
3. SELECT * FROM create_hypertable('new_table', 'time');
4. INSERT INTO new_table (SELECT * FROM ordinary_table) ;

(i.e., that's migration.  Leave off step 4 if you don't need to migrate, and just specify the schema like normal in step 2.) 

Let us know if there's anything we can help with :)

**Comment by prolic** [comment]
Give it a try and let travis test it, too?

**Comment by prolic** [comment]
As there is nothing done here, I am closing this issue. If someone wants to give it a try, feel free to open a pull request.
