### ISSUE TITLE
Invalid DB_HOST in phpunit files when using docker-compose to run the tests.

### ISSUE THREAD

**Issue by bweston92** [prooph/pdo-event-store#90]
The DB_HOST is set to `127.0.0.1` which doesn't relate to the host machine or the database containers just the `composer` container setting to `mysql` in `phpunit.xml.mysql` works as expected. Obviously for travis this won't work.

We can either use the `host` network driver but this will probably annoy developers that already use these ports.

**Comment by prolic** [comment]
Any ideas? I think users can edit their files for local testing if needed.

**Comment by bweston92** [comment]
I've managed to do it in the composer.json script and it doesn't effect Travis either so maybe a win win.
