### ISSUE TITLE
[Projections] ERROR:  value too long for type character(26)

### ISSUE THREAD

**Issue by Lctrs** [prooph/pdo-event-store#98]
While working on a new project, I noticed that my docker containers running my projections died after a random amount of time with the following error : 

`[2017-07-07 16:55:37] console.ERROR: Error thrown while running command "my_command_name". Message: "Error 22001. Maybe the projection table is not setup? Error-Info: ERROR:  value too long for type character(26)" {"error":"[object] (Prooph\\EventStore\\Exception\\RuntimeException(code: 0): Error 22001. Maybe the projection table is not setup?\nError-Info: ERROR:  value too long for type character(26) at /srv/app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreReadModelProjector.php:727)","command":"my_command_name","message":"Error 22001. Maybe the projection table is not setup?\nError-Info: ERROR:  value too long for type character(26)"} []`

Further debugging revealed that, sometimes, the variable `$lockUntilString` in `PdoEventStoreReadModelProjector::updateLock()` holds a string that is 27 char long (for example in my case : `2017-07-07T16:55:37.1000000`).

I'm running PHP 7.1.7 in Alpine with PostgreSQL as database.

**Comment by prolic** [comment]
1000000 microseconds is a second. So this should never happen. Maybe it's a PHP bug? I am not sure yet. Will do some testing.

**Comment by Lctrs** [comment]
Yet it happened. For debugging, I just manually added the value of `$lockUntilString` to the error message, waited for the error to happen, and got this value. I'll do some research for a PHP bug.

Just in case, here is my full debug error message : 

`[2017-07-07 16:55:37] console.ERROR: Error thrown while running command "my_command_name". Message: "Error 22001. Maybe the projection table is not setup? Error-Info: ERROR:  value too long for type character(26) (lockUntilString is : "2017-07-07T16:55:37.1000000")" {"error":"[object] (Prooph\\EventStore\\Exception\\RuntimeException(code: 0): Error 22001. Maybe the projection table is not setup?\nError-Info: ERROR:  value too long for type character(26) (lockUntilString is : \"2017-07-07T16:55:37.1000000\") at /srv/app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreReadModelProjector.php:727)","command":"my_command_name","message":"Error 22001. Maybe the projection table is not setup?\nError-Info: ERROR:  value too long for type character(26) (lockUntilString is : \"2017-07-07T16:55:37.1000000\")"} []`

**Comment by prolic** [comment]
I found the problem, working on a fix...

**Comment by prolic** [comment]
@Lctrs Can you test my PR https://github.com/prooph/pdo-event-store/pull/99 and tell me how it's working for you?
